export const languages = [
  {name: 'chinese', iso: 'CN'},
  {name: 'mandarin', iso: 'CN'},
  {name: 'Spanish', iso: 'ES'},
  {name: 'English', iso: 'GB'},
  {name: 'Hindi', iso: 'IN'},
  {name: 'Arabic', iso: 'SA'},
  {name: 'Portuguese', iso: 'PT'},
  {name: 'Russian', iso: 'RU'},
  {name: 'Japanese', iso: 'JP'},
  {name: 'Korean', iso: 'KP'},
  {name: 'French', iso: 'FR'},
  {name: 'German', iso: 'DE'},
  {name: 'Italian', iso: 'IT'},
  {name: 'Ukrainian', iso: 'UA'},
  {name: 'Dutch', iso: 'NL'},
  {name: 'Swedish', iso: 'SE'},
  {name: 'Norwegian', iso: 'NO'},
];
